version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ../src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "fwa"
      POSTGRES_USER: "fwa"
      POSTGRES_PASSWORD: "password"
  web:
    build: ./cinema
    image: cinema:1.0
    container_name: web
    volumes:
      - ../target/cinema.war:/usr/local/tomcat/webapps/cinema.war
#    entrypoint:
#      - "catalina.sh"
#      - "run"
    ports:
      - '8082:8080'
    environment:
      POSTGRES_DB: "fwa"
      POSTGRES_USER: "fwa"
      POSTGRES_PASSWORD: "password"
      POSTGRES_URL: "jdbc:postgresql://db:5432/fwa"