version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ../src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: fwa
      POSTGRES_USER: fwa
      POSTGRES_PASSWORD: password
  web:
    depends_on:
      - db
    image: tomcat:9.0.56-jdk8-corretto
    volumes:
      - ../target/cinema.war:/usr/local/tomcat/webapps/cinema.war
    ports:
      - '8082:8080'
    environment:
      POSTGRES_DB: fwa
      POSTGRES_USER: fwa
      POSTGRES_PASSWORD: password