version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "fwa"
      POSTGRES_USER: "fwa"
      POSTGRES_PASSWORD: "password"
networks:
  default:
    external: true
    name: cinemanetwork